import React from 'react';

interface Props {
  darkMode: boolean;
  onBack: () => void;
}

const PrivacyPolicy: React.FC<Props> = ({ darkMode, onBack }) => {
  return (
    <div className={`w-full max-w-4xl mx-auto px-6 py-12 animate-fade-in ${darkMode ? 'text-slate-300' : 'text-slate-700'}`}>
      <button onClick={onBack} className="mb-8 flex items-center text-sm font-bold text-indigo-500 hover:text-indigo-600 transition-colors">
        <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
        Back to Home
      </button>
      <h1 className={`text-4xl font-extrabold mb-8 ${darkMode ? 'text-white' : 'text-slate-900'}`}>Privacy Policy</h1>
      
      <div className="space-y-8 text-sm leading-relaxed border-l-2 pl-6 border-slate-200 dark:border-slate-700">
        <section>
          <h2 className={`text-xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-slate-900'}`}>1. Information We Collect</h2>
          <p>We collect information you provide directly to us when using CareerStealth, specifically the resume content you upload and the job descriptions you input. We do not store this data permanently on our servers; it is processed in real-time for the purpose of analysis.</p>
        </section>

        <section>
          <h2 className={`text-xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-slate-900'}`}>2. How We Use Information</h2>
          <p>We use the information to provide resume analysis, optimization suggestions, and "roasts" generated by AI. We do not sell your personal data to third parties. All processing is done to deliver the core functionality of the application.</p>
        </section>

        <section>
          <h2 className={`text-xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-slate-900'}`}>3. AI Processing</h2>
          <p>Your data is processed using Google's Gemini API. Please refer to Google's privacy policy regarding how they handle data processed through their AI models. Data sent to the AI is transient and used solely for generating the analysis response.</p>
        </section>
        
        <section>
            <h2 className={`text-xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-slate-900'}`}>4. Local Storage</h2>
            <p>We use your browser's Local Storage to save your session state so you don't lose progress if you refresh the page. This data resides entirely on your device. You can clear this at any time via your browser settings.</p>
        </section>

        <section>
            <h2 className={`text-xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-slate-900'}`}>5. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us:</p>
            <ul className="mt-2 space-y-1">
                <li>GitHub: <a href="https://github.com/MustafaMiyaji" target="_blank" className="text-indigo-500 hover:underline">MustafaMiyaji</a></li>
                <li>LinkedIn: <a href="https://www.linkedin.com/in/mustafa-alimiyaji-195742327/" target="_blank" className="text-indigo-500 hover:underline">Mustafa Miyaji</a></li>
            </ul>
        </section>
      </div>
      
      <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-700 text-xs opacity-60">
        <p>Last Updated: {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;